<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>resources\mouseshake.ico</ApplicationIcon>
    <AssemblyName>MotionSentinel</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
  <EmbeddedResource Include="resources\mouseshake.ico" />
</ItemGroup>

</Project>
